# Generated by Django 2.2.5 on 2019-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IT', 'IT & Gadget'), ('FA', 'Fashion'), ('EL', 'Electronics')], max_length=2),
        ),
    ]
