# Generated by Django 2.2.5 on 2019-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20190916_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FA', 'Fashion'), ('IT', 'IT & Gadget')], max_length=2),
        ),
    ]
