# Generated by Django 2.0 on 2019-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20190917_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IT', 'IT & Gadget'), ('EL', 'Electronics'), ('FA', 'Fashion')], max_length=2),
        ),
    ]
